spring:
  threads:
    virtual:
      enabled: true
  application:
    name: racing
  datasource:
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'
      maximum-pool-size: 50
      minimum-idle: 10
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  servlet:
    context-path: /races

racing:
  engine:
    url: https://click-racer-983614458473.europenorth1.run.app/api/fragile-fast/points/earn
    fallback-url: https://click-racer-983614458473.europenorth1.run.app/api/stable-slow/points/earn
    connect-timeout-seconds: 3
    read-timeout-seconds: 5
  reporting:
    url: https://click-racer-983614458473.europenorth1.run.app/api/fragile-fast/reporting/winners
    fallback-url: https://click-racer-983614458473.europenorth1.run.app/api/stable-slow/reporting/winners
    connect-timeout-seconds: 3
    read-timeout-seconds: 10
  game:
    oil-slick-cost: 10
    engine-hack-cost: 20
    freeze-percentage: 0.01
    hack-penalty-limit: 11